<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:include filename="geometry.xacro"/>
    <xacro:include filename="inertial.xacro"/>

	<!-- DAE image of finger manipulator -->
    <xacro:macro name="finger" params="type:=''">
        <mesh filename="file://$(arg meshDir)/l_finger_${type}.dae" scale="0.5 0.5 0.5"/>
    </xacro:macro>

    <!-- DEFINITION MACROS -->
    <xacro:macro name="articulation" params="mass radius length position:='0 0 0' rotation:='0 0 0'">
        <visual>
            <origin xyz="${position}" rpy="${rotation}"/>
            <geometry>
                <cylinder length="${length}" radius="${radius}" />
            </geometry>
            <material name="PurpleOne"/>
        </visual>
        <collision>
            <origin xyz="${position}" rpy="${rotation}"/>
            <geometry>
                <cylinder length="${length}" radius="${radius}" />
            </geometry>
        </collision>
         <xacro:inertial_cylinder  
            mass="${mass}" 
            length="${length}"
            radius="${radius}">
            <origin xyz="${position}" rpy="${rotation}"/>
        </xacro:inertial_cylinder>
    </xacro:macro>

    <xacro:macro name="articulation_end_effector" params="mass radius position:='0 0 0' rotation:='0 0 0'">
        <visual>
            <origin xyz="${position}" rpy="${rotation}"/>
            <geometry>
                <sphere radius="${radius}"/>
            </geometry>
            <material name="WhiteOne"/>
        </visual>
        <collision>
            <origin xyz="${position}" rpy="${rotation}"/>
            <geometry>
                <sphere radius="${radius}"/>
            </geometry>
        </collision>
         <xacro:inertial_sphere  
            mass="${mass}" 
            radius="${radius}">
            <origin xyz="${position}" rpy="${rotation}"/>
        </xacro:inertial_sphere>
    </xacro:macro>

    <xacro:macro name="manipulator" params="length position rotate">
        <visual>
            <origin xyz="${position}" rpy="${rotate}"/>
            <geometry>
                <cylinder length="${length}" radius="${manipulator_radius}" />
            </geometry>
            <material name="BlueOne"/>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <cylinder length="${length}" radius="${manipulator_radius}" />
            </geometry>
        </collision>
        <!-- Calculate actual manipulator's mass (in Kg)-->
        <xacro:property 
            name="manipulator_mass" 
            value="${(pi * ((manipulator_radius*2)**2)/4)*length * manipulator_mass_density}" 
        /> 
        <DEBUG length_="${length}" mass_="${round(manipulator_mass, 5)}"/>
        <xacro:inertial_cylinder 
            mass="${manipulator_mass}" 
            length="${length}" 
            radius="${manipulator_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </xacro:macro>

    <xacro:macro name="gripper_part_link" params="name_prefix reflect">
        <link name="${name_prefix}_gripper">
        <visual>
            <origin rpy="${(reflect-1)/2*pi} 0 0" xyz="0 0 0"/>
            <geometry>
                <xacro:finger />
            </geometry>
        </visual>
        <collision>
            <geometry>
                <xacro:finger />
            </geometry>
            <origin rpy="${(reflect-1)/2*pi} 0 0" xyz="0 0 0"/>
        </collision>
        <xacro:inertial_default mass="${gripper_mass}"/>
        </link>

        <link name="${name_prefix}_tip">
        <visual>
            <origin rpy="${(reflect-1)/2*pi} 0 0" xyz="0.046 0.0039 0"/>
            <geometry>
                <xacro:finger type="tip"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <xacro:finger type="tip"/>
            </geometry>
            <origin rpy="${(reflect-1)/2*pi} 0 0" xyz="0.09137 0.00495 0"/>
        </collision>
        <xacro:inertial_default mass="${gripper_mass}"/>
        </link>
    </xacro:macro>

    <xacro:macro name="gripper_link" params="side turn_in_percent">
        <xacro:property name="reflect_" value="1"/>
        <xacro:property name="value" value="${(turn_in_percent * gripper_reflect_base) / 100}" />
        <xacro:if value="${side == 'left'}">
            <xacro:property name="reflect_" value="-1"/>
        </xacro:if>
        <xacro:gripper_part_link 
            name_prefix="${side}_up" 
            reflect="${ gripper_reflect_base + reflect_ * value }" />
        <xacro:gripper_part_link 
            name_prefix="${side}_down" 
            reflect="${ -gripper_reflect_base + reflect_ * value }" />
    </xacro:macro>

    <xacro:macro name="gripper_part_joint" params="name_prefix reflect *parent">
        <joint name="${name_prefix}_gripper_joint" type="revolute">
            <axis xyz="0 0 ${reflect}"/>
            <limit effort="1000.0" lower="0.0" upper="0.548" velocity="0.5"/>
            <origin rpy="0 0 0" xyz="${articulation_end_effector_radius/2} ${reflect*0.01} 0"/>
            <xacro:insert_block name="parent" />
            <child link="${name_prefix}_gripper"/>
        </joint>
        <joint name="${name_prefix}_tip_joint" type="fixed">
            <parent link="${name_prefix}_gripper" />
            <child link="${name_prefix}_tip"/>
        </joint>
    </xacro:macro>

    <!--Definition of full gripper by side-->
    <xacro:macro name="gripper_joint" params="side to_link">
        <xacro:gripper_part_joint name_prefix="${side}_up" reflect="1">
            <parent link="${to_link}"/>
        </xacro:gripper_part_joint>
        <xacro:gripper_part_joint name_prefix="${side}_down" reflect="-1" >
            <parent link="${to_link}"/>
        </xacro:gripper_part_joint>
    </xacro:macro>

    <!--Definition of DoF manipulator by side-->
    <xacro:macro name="DoF_manipulator" params="side">
        <xacro:property name="factor_by_side" value="1"/>
        <xacro:if value="${side == 'left'}">
            <xacro:property name="factor_by_side" value="-1"/>
        </xacro:if>

        <!--BASE ARTICULATION-->
        <link name="articulation_base_${side}">
            <xacro:articulation
                mass="${base_articulation_mass}" 
                radius="${base_articulation_radius}" 
                length="${base_articulation_length}" 
                position ="0 0 0" 
                rotation="${pi/2} 0 0"
            />
        </link>

        <!-- BASE (FIRST) MANIPULATOR ## -->
        <link name="manipulator_1st_${side}">
            <xacro:manipulator 
                position="0 0 0"
                rotate="${factor_by_side * -(pi/2)} 0 0"
                length="${manipulator_1st_length}"
            />
        </link>

        <!-- FIRST ARTICULATION -->
        <link name="articulation_1st_${side}">
            <xacro:articulation 
                mass="${articulation_mass}" 
                radius="${articulation_radius}" 
                length="${articulation_length}" 
            />
        </link>

        <link name="manipulator_2nd_${side}">
            <xacro:manipulator 
                position="0 0 0"
                rotate="0 ${pi/2} 0"
                length="${manipulator_2nd_length}"
            />
        </link>
                        
        <!-- SECOND ARTICULATION -->
        <link name="articulation_2nd_${side}">
            <xacro:articulation 
                mass="${articulation_mass}" 
                radius="${articulation_radius}" 
                length="${articulation_length}" 
            />
        </link>

        <link name="manipulator_3rd_${side}">
            <xacro:manipulator 
                position="${manipulator_3rd_length/2} 0 0"
                rotate="0 ${pi/2} 0"
                length="${manipulator_3rd_length}"
                />
        </link>

        <!-- THIRD ARTICULATION FOR END EFFECTOR  -->
        <link name="articulation_3rd_${side}">
            <xacro:articulation_end_effector
                mass="${articulation_end_effector_mass}" 
                radius="${articulation_end_effector_radius}" 
            />
        </link>

        <xacro:gripper_link side="${side}" turn_in_percent="10"/>
    </xacro:macro>

    <!--IMPLEMENTATION-->
    <!-- LEFT MANIPULATOR -->
    <xacro:DoF_manipulator side="left" />

    <!-- RIGHT MANIPULATOR -->
    <xacro:DoF_manipulator side="right" />

</robot>