camera_matrix:
  cols: !!int 3
  data: [438.8, 0.0, 305.6, 0.0, 437.3, 243.7, 0.0, 0.0, 1.0]
  rows: !!int 3
camera_name: "camera_front"
distortion_coefficients:
  cols: !!int 5
  data: [-0.36, 0.11, 0.001, 0.000505, 0.0]
  rows: !!int 1
distortion_model: plumb_bob
image_height: !!int 480
image_width: !!int 640
projection_matrix:
  cols: !!int 4
  data: [393.6538, 0.0, 322.79794, 0.0, 0.0, 393.654, 241.091, 0.0, 0.0, 0.0, 1.0,\
    \ 0.0]
  rows: !!int 3
rectification_matrix:
  cols: !!int 3
  data: [0.99998, 0.0028, -0.00605, -0.0028, 0.999986, -0.0044, 0.006, 0.0044,\
    \ 0.99997]
  rows: !!int 3
