<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- MACROS -->
    <xacro:macro name="box_panel" params="mass d w h position rotate *material **center_mass">
        <visual>
            <origin xyz="${position}" rpy="${rotate}"/>
            <geometry>
                <box size="${w} ${d} ${h}"/>
            </geometry>
             <xacro:insert_block name="material" />
        </visual>
        <collision>
            <origin xyz="${position}" rpy="${rotate}"/>
            <geometry>
                <box size="${w} ${d} ${h}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="${mass}" />
            <inertia 
                    ixx="${(1.0/12) * mass * float(w**2+h**2)}" ixy="0.0" ixz="0.0"
                    iyy="${(1.0/12) * mass * float(d**2+h**2)}" iyz="0.0"
                    izz="${(1.0/12) * mass * float(d**2+w**2)}"
            />
            <xacro:insert_block name="center_mass" />
        </inertial>
    </xacro:macro>
    
    <xacro:macro name="box_gripper" params="side">
       <link name="box_gripper_${side}">
            <visual>
                <origin rpy="${pi/2} .0 .0"/>
                <geometry>
                    <cylinder radius="${box_gripper_radius}" length="${box_gripper_length}" />
                </geometry>
                <material name="YellowOne"/>
            </visual>
            <collision>
                <origin/>
                <geometry>
                    <cylinder radius="${box_gripper_radius}" length="${box_gripper_length}" />
                </geometry>
            </collision>
            <xacro:inertial_cylinder 
                mass="${box_gripper_mass}" 
                length="${box_gripper_length}" 
                radius="${box_gripper_radius}">
                <origin rpy="${pi/2} .0 .0"/>
            </xacro:inertial_cylinder>
        </link>
        <link name="box_gripper_holder_${side}">
            <visual>
                <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
                <geometry>
                    <cylinder length="${box_gripper_holder_length}" radius="${box_gripper_holder_radius}" />
                </geometry>
                <material name="BlueOne"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${box_gripper_holder_length}" radius="${box_gripper_holder_radius}" />
                </geometry>
            </collision>
            <xacro:inertial_cylinder 
                mass="${box_gripper_holder_mass}" 
                length="${box_gripper_holder_length}" 
                radius="${box_gripper_holder_radius}">
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </xacro:inertial_cylinder>
        </link>
        <xacro:gazeboGreyColorBlock link="box_gripper_holder_${side}"/>
    </xacro:macro>

    <!-- PANEL BACK LINK-->
    <link name="box_panel_back">
        <xacro:box_panel 
            mass="${box_panel_mass}" 
            d="${box_panel_fb_depth}" 
            w="${box_panel_fb_width}" 
            h="${box_panel_fb_height}"
            position="0 0 ${box_panel_fb_height/2}"
            rotate="0 0 ${pi/2}">
            <material name="YellowOne"/>
            <center_mass>
                <origin xyz=".0 .0 ${box_panel_fb_height/3}"/>
            </center_mass>
        </xacro:box_panel>
    </link>
    <xacro:gazeboBackroundStickerBlock link="box_panel_back"/>

    <!-- PANEL FRONT LINK-->
    <link name="box_panel_front">
        <xacro:box_panel 
            mass="${box_panel_mass}" 
            d="${box_panel_fb_depth}" 
            w="${box_panel_fb_width}" 
            h="${box_panel_fb_height}"
            position="-${box_panel_fb_depth/2} 0 ${box_panel_fb_height/2}"
            rotate="0 0 ${pi/2}">
            <material name="YellowOne"/>
            <center_mass>
                <origin xyz="-${box_panel_fb_depth/2} .0 ${box_panel_fb_height/3}"/>
            </center_mass>
        </xacro:box_panel>
    </link>
    <xacro:gazeboBackroundStickerBlock link="box_panel_back"/><!--  -->

    <!-- PANEL LEFT LINK-->
    <link name="box_panel_left">
        <xacro:box_panel 
            mass="${box_panel_mass}" 
            d="${box_panel_lr_depth - box_panel_fb_depth*2}" 
            w="${box_panel_lr_width}" 
            h="${box_panel_lr_height}"
            position=".0 -${box_panel_lr_width/2} ${box_panel_fb_height/2}"
            rotate=".0 .0 ${pi/2}">
            <material name="YellowOne"/>
            <center_mass>
                <origin xyz=".0 -${box_panel_lr_width/2} ${box_panel_lr_height/3}"/>
            </center_mass>
        </xacro:box_panel>
    </link>
    <xacro:gazeboStickerBlock link="box_panel_left"/>

    <!-- PANEL RIGHT LINK-->
    <link name="box_panel_right">
        <xacro:box_panel 
            mass="${box_panel_mass}" 
            d="${box_panel_lr_depth - box_panel_fb_depth*2}" 
            w="${box_panel_lr_width}" 
            h="${box_panel_lr_height}"
            position=".0 ${box_panel_lr_width/2} ${box_panel_fb_height/2}"
            rotate=".0 .0 ${pi/2}">
            <material name="YellowOne"/>
            <center_mass>
                <origin xyz=".0 ${box_panel_lr_width/2} ${box_panel_lr_height/3}"/>
            </center_mass>
        </xacro:box_panel>
    </link>
    <xacro:gazeboStickerBlock link="box_panel_right"/>

    <!-- PANEL TOP LINK-->
    <link name="box_panel_top">
        <xacro:box_panel 
            mass="${box_panel_mass * 1/3}" 
            d="${box_panel_top_depth}" 
            w="${box_panel_top_width}" 
            h="${box_panel_top_height}"
            position="${box_panel_top_depth/2} .0 ${box_panel_top_height/2}"
            rotate=".0 .0 ${pi/2}">
            <material name="YellowOne"/>
            <center_mass>
                <origin xyz="${box_panel_top_depth/2} .0 .0" rpy=".0 .0 ${pi/2}"/>
            </center_mass>
        </xacro:box_panel>
    </link>

    <!-- HINGE COVER LINK-->
    <link name="hinge_cover">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 ${pi/2}"/>
            <geometry>
                <cylinder radius="${hinge_cover_radius}" length="${hinge_cover_length}"/>
            </geometry>
            <material name="GreenOne"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${hinge_cover_radius}" length="${hinge_cover_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${hinge_cover_mass}" length="${hinge_cover_length}" radius="${hinge_cover_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- BOX COVER LINK -->
    <link name="box_cover">
        <xacro:box_panel 
            mass="${box_panel_mass * 1/3}" 
            d="${box_cover_depth}" 
            w="${box_cover_width}" 
            h="${box_cover_height}"
            position="${box_cover_depth/2} .0 .0"
            rotate=".0 .0 ${pi/2}">
            <material name="GreenOne"/>
            <center_mass>
                <origin xyz="${box_cover_depth/2} .0 .0" rpy=".0 .0 ${pi/2}"/>
            </center_mass>
        </xacro:box_panel>
    </link>
    
    <!-- BOX GRIPPER LEFT LINK-->
    <xacro:box_gripper side="left" />

    <!-- BOX GRIPPER RIGHT LINK-->
    <xacro:box_gripper side="right" />

    <!-- HOOD LEFT LINK-->
    <link name="hood_left">
        <xacro:box_panel 
            mass="${hood_panel_mass}" 
            d="${hood_lr_depth}" 
            w="${hood_lr_width}" 
            h="${hood_lr_min_height}"
            position="0 -${hood_lr_width/2} ${hood_fb_height/2}"
            rotate="0 0 ${pi/2}">
            <material name="OrangeOne"/>
            <center_mass>
                <origin xyz=".0 .0 ${hood_lr_min_height/3}" rpy=".0 .0 .0"/>
            </center_mass>
        </xacro:box_panel>
    </link>

    <!-- HOOD RIGHT LINK-->
    <link name="hood_right">
        <xacro:box_panel 
            mass="${hood_panel_mass}" 
            d="${hood_lr_depth}" 
            w="${hood_lr_width}" 
            h="${hood_lr_min_height}"
            position="0 ${hood_lr_width/2} ${hood_fb_height/2}"
            rotate=".0 .0 ${pi/2}">
            <material name="OrangeOne"/>
            <center_mass>
                <origin xyz=".0 ${hood_lr_width/2} ${hood_lr_min_height/3}" rpy=".0 .0 .0"/>
            </center_mass>
        </xacro:box_panel>
    </link>

    <!-- HOOD FRONT LINK-->
    <link name="hood_front">
        <xacro:box_panel 
            mass="${hood_panel_mass}" 
            d="${hood_fb_depth}" 
            w="${hood_fb_width}" 
            h="${hood_fb_height}"
            position="-${hood_fb_depth/2} 0 ${hood_fb_height/2}"
            rotate="0 0 ${pi/2}">
            <material name="OrangeOne"/>
            <center_mass>
                <origin xyz="-${hood_fb_depth/2} .0 ${hood_fb_height/3}" rpy=".0 .0 .0"/>
            </center_mass>
        </xacro:box_panel>
    </link>

    <!-- HOOD TOP LINK-->
    <link name="hood_top">
        <xacro:box_panel 
            mass="${hood_panel_mass/2}" 
            d="${hood_top_depth}" 
            w="${hood_top_width}" 
            h="${hood_top_height}"
            position="${hood_top_depth/2} .0 -${hood_top_height/2}"
            rotate=".0 .0 ${pi/2}">
            <material name="OrangeOne"/>
            <center_mass>
                <origin xyz="${hood_top_depth/2} .0 .0" rpy=".0 .0 ${pi/2}"/>
            </center_mass>
        </xacro:box_panel>
    </link>

    <!-- HOOD BAFFLE LINK (GLASS)-->
    <link name="hood_baffle">
        <xacro:box_panel 
            mass="${hood_panel_mass/3}" 
            d="${hood_baffle_depth}" 
            w="${hood_baffle_width}" 
            h="${hood_baffle_height}"
            position=".0 .0 .0"
            rotate="-${pi/5} .0 ${pi/2}">
            <material name="GreyTransparentOne"/>
            <center_mass>
                <origin xyz="${hood_baffle_depth} .0 .0"/>
            </center_mass>
        </xacro:box_panel>
    </link>

    <!-- BOX LADLE LINK-->
    <link name="box_ladle_front">
        <xacro:box_panel 
            mass="${box_bracket_ladle_mass}" 
            d="${box_bracket_ladle_depth}" 
            w="${box_bracket_ladle_width}" 
            h="${box_bracket_ladle_height}"
            position="0 0 0"
            rotate="0 0 ${pi/2}">
            <material name="GreenOne"/>
            <center_mass>
                <origin xyz="0 0 0"/>
            </center_mass>
        </xacro:box_panel>
    </link>

    <!-- BOX LADLE BRACKET HOLDER LEFT LINK-->
    <link name="box_bracket_holder_left">
        <xacro:box_panel 
            mass="${box_bracket_holder_mass}" 
            d="${box_bracket_holder_depth}" 
            w="${box_bracket_holder_width}" 
            h="${box_bracket_holder_height}"
            position="0 0 0"
            rotate="0 0 0">
            <material name="RedOne"/>
            <center_mass>
                <origin xyz=".0 .0 .0"/>
            </center_mass>
        </xacro:box_panel>
    </link>

    <!-- BOX LADLE BRACKET HOLDER RIGHT LINK-->
    <link name="box_bracket_holder_right">
        <xacro:box_panel 
            mass="${box_bracket_holder_mass}" 
            d="${box_bracket_holder_depth}" 
            w="${box_bracket_holder_width}" 
            h="${box_bracket_holder_height}"
            position="0 0 0"
            rotate="0 0 0">
            <material name="RedOne"/>
            <center_mass>
                <origin xyz=".0 .0 .0" rpy=".0 .0 .0"/>
            </center_mass>
        </xacro:box_panel>
    </link>
</robot>
