<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <gazebo>
        <!-- DEPRECATED (ros1 control compatibility) -->
         <plugin name='differential_drive_controller' filename='libgazebo_ros_diff_drive.so'>
    
            <num_wheel_pairs>2</num_wheel_pairs>

            <left_joint>front_left_wheel_joint</left_joint>
            <right_joint>front_right_wheel_joint</right_joint>

            <left_joint>back_left_wheel_joint</left_joint>
            <right_joint>back_right_wheel_joint</right_joint>

            <wheel_diameter>${wheel_radius*2}</wheel_diameter>
            <wheel_separation>${axle_length - wheel_length/2 - wheel_screw}</wheel_separation>
            <DEBUG diam_="${wheel_radius*2}" sep_="${axle_length - wheel_length/2 - wheel_screw}" axle_="${axle_length}"/>
    
            <max_wheel_torque>30</max_wheel_torque>
            <max_wheel_acceleration>5.0</max_wheel_acceleration>    

            <robot_base_frame>base_link</robot_base_frame>
            <odometry_frame>odom</odometry_frame>

            <publish_odom>true</publish_odom>
            <publish_odom_tf>true</publish_odom_tf>
            <publish_wheel_tf>true</publish_wheel_tf>
            
            <ros>
                <remapping>cmd_vel:=/differential_drive_controller/cmd_vel_unstamped</remapping>
            </ros>
        </plugin>

    </gazebo>

</robot>