<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- PROPETIES -->

    <!-- FULL BOX PARAMS -->
    <xacro:property name="box_width" value="0.4" />
    <xacro:property name="box_height" value="0.3" />
    <xacro:property name="box_depth" value="0.6" />
    <xacro:property name="box_full_mass" value="30" />

    <!-- CHASSIS PARAMS-->
    <xacro:property name="chassis_depth" value="${box_depth}" />
    <xacro:property name="chassis_hood_depth" value="${box_depth/3.7}" />
    <xacro:property name="chassis_box_depth" value="${box_depth - chassis_hood_depth}" />
    <xacro:property name="chassis_width" value="${box_width}" />
    <xacro:property name="chassis_height" value="0.05" />
    <xacro:property name="chassis_mass" value="0.5" />

    <!-- BOX PANEL PARAMS-->
    <xacro:property name="box_panel_mass" value="${box_full_mass/(6*3)}" />
    <xacro:property name="box_panel_thickness" value=".03" />
    <!-- ... FRONT-BACK -->
    <xacro:property name="box_panel_fb_width" value="${box_width}" />
    <xacro:property name="box_panel_fb_height" value="${box_height}" />
    <xacro:property name="box_panel_fb_depth" value="${box_panel_thickness}" />
    <!-- ... LEFT-RIGHT -->
    <xacro:property name="box_panel_lr_width" value="${box_panel_thickness}" />
    <xacro:property name="box_panel_lr_height" value="${box_height}" />
    <xacro:property name="box_panel_lr_depth" value="${chassis_box_depth}" />
    <!-- ... TOP -->
    <xacro:property name="box_panel_top_width" value="${box_width}" />
    <xacro:property name="box_panel_top_height" value="${box_panel_thickness/2}" />
    <xacro:property name="box_panel_top_depth" value="${chassis_box_depth * 1/3}" />
    <!-- ... COVER -->
    <xacro:property name="box_cover_width" value="${box_width}" />
    <xacro:property name="box_cover_height" value="${box_panel_thickness}" />
    <xacro:property name="box_cover_depth" value="${chassis_box_depth - box_panel_top_depth - hinge_cover_radius}" />

    <!-- HOOD BOX PARAMS -->
    <xacro:property name="hood_full_mass" value="${box_full_mass/6}" />
    <xacro:property name="hood_panel_mass" value="${hood_full_mass/4}" />
    <!-- ... LEFT-RIGHT -->
    <xacro:property name="hood_lr_depth" value="${chassis_hood_depth}" />
    <xacro:property name="hood_lr_width" value="${box_panel_thickness}" />
    <xacro:property name="hood_lr_max_height" value="${box_height}" />
    <xacro:property name="hood_lr_min_height" value="${hood_lr_max_height - hood_lr_max_height*1/3}" />
    <!-- ... FRONT-BACK -->
    <xacro:property name="hood_fb_width" value="${box_width}" />
    <xacro:property name="hood_fb_height" value="${hood_lr_min_height}" />
    <xacro:property name="hood_fb_depth" value="${box_panel_thickness}" />
    <!-- ... TOP -->
    <xacro:property name="hood_top_width" value="${box_width}" />
    <xacro:property name="hood_top_height" value="${box_panel_thickness}" />
    <xacro:property name="hood_top_depth" value="${chassis_hood_depth/2}" />
    <!-- ... TOP BAFFLE -->
    <xacro:property name="hood_baffle_width" value="${box_width}" />
    <xacro:property name="hood_baffle_height" value="${sqrt((hood_lr_max_height - hood_lr_min_height + box_panel_thickness)**2 + hood_top_depth**2)}" />
    <xacro:property name="hood_baffle_depth" value="${box_panel_thickness/2}" />

    <!-- BOX GRIPPERS PARAMS-->
    <xacro:property name="box_gripper_mass" value="${box_panel_mass/5}" />
    <xacro:property name="box_gripper_radius" value="${box_gripper_holder_radius*1.2}" />
    <xacro:property name="box_gripper_length" value="${box_panel_thickness/3}" />
    <!-- ... BOX GRIPPER HOLDER -->
    <xacro:property name="box_gripper_holder_radius" value="${(box_height/7 - ((box_height/7) * 1/2.8))/2}" />
    <xacro:property name="box_gripper_holder_length" value="0.015" />
    <xacro:property name="box_gripper_holder_mass" value="${box_gripper_mass}" />
    <!-- BOX LADLE PARAMS-->
    <!-- ... BOX BRACKET -->
    <xacro:property name="box_bracket_ladle_mass" value="${box_panel_mass/5}" />
    <xacro:property name="box_bracket_ladle_depth" value="${box_panel_thickness/2}" />
    <xacro:property name="box_bracket_ladle_width" value="${box_width - box_panel_thickness*2}" />
    <xacro:property name="box_bracket_ladle_height" value="${hood_lr_min_height/3}" />
    <!-- ... BRACKET HOLDERS-->
    <xacro:property name="box_bracket_holder_mass" value="${box_panel_mass/10}" />
    <xacro:property name="box_bracket_holder_depth" value="${box_panel_thickness}" />
    <xacro:property name="box_bracket_holder_width" value="${box_panel_thickness}" />
    <xacro:property name="box_bracket_holder_height" value="${box_panel_thickness}" />

    <!-- GRIPPER PARAMS-->
    <xacro:property name="gripper_mass" value="0.001" />
    <xacro:property name="gripper_tip_mass" value="${gripper_mass/3}" />
    <xacro:property name="gripper_reflect_base" value="1" />

    <!-- HINGE COVER -->
    <xacro:property name="hinge_cover_mass" value="0.2" />
    <xacro:property name="hinge_cover_radius" value="0.02" />
    <xacro:property name="hinge_cover_length" value="${box_width}" />

    <!-- ARTICULATION PARAMS-->
    <!-- ... BASE PARAMS-->
    <xacro:property name="base_articulation_radius" value="${box_gripper_holder_radius*1.2}" />
    <xacro:property name="base_articulation_length" value="0.007" />
    <xacro:property name="base_articulation_mass" value="${box_gripper_holder_mass}" />
    <!-- ... JOINT PARAMS-->
    <xacro:property name="articulation_radius" value="${base_articulation_radius/1.2}" />
    <xacro:property name="articulation_length" value="${manipulator_radius*4 + (manipulator_radius * 1/2)}" />
    <xacro:property name="articulation_mass" value="${base_articulation_mass/2}" />
    <!-- ... END EFFECTOR PARAMS-->
    <xacro:property name="articulation_end_effector_radius" value="0.014" />
    <xacro:property name="articulation_end_effector_mass" value="${base_articulation_mass/2}" />
    
    <!-- MANIPULATOR PARAMS -->
    <xacro:property name="manipulator_mass_density" value="1000" /> <!-- плотность (кг/м3)-->
    <xacro:property name="manipulator_radius" value="${articulation_radius - (articulation_radius/10)}" />
    <xacro:property name="manipulator_1st_length" value="${box_height/10}" />
    <xacro:property name="manipulator_2nd_length" value="${box_height/1.5}" />
    <xacro:property name="manipulator_3rd_length" value="${box_width/2}" />

    <!-- WHEELS PARAMS-->
    <xacro:property name="wheel_radius" value="${box_depth * 1/6.5}" />
    <xacro:property name="wheel_length" value="0.04" />
    <xacro:property name="wheel_mass" value="2" />
    <xacro:property name="wheel_screw" value="${wheel_length/8}" />

    <!-- AXLE PARAMS-->
    <xacro:property name="axle_length" value="${box_width + wheel_length*2 + 0.02 + wheel_screw*2}" />
    <xacro:property name="axle_radius" value="0.01" />
    <xacro:property name="axle_mass" value="0.015" />

    <!-- LADLE PARAMS-->
    <xacro:property name="ladle_plate_mass" value="1.0" />
    <xacro:property name="ladle_plate_depth" value="${box_panel_thickness/2}" />
    <xacro:property name="ladle_plate_width" value="${box_width}" />
    <xacro:property name="ladle_plate_height" value="${box_height/4}" />
    <!-- .. SLEEVE (FOR PLATES) -->
    <xacro:property name="ladle_sleeve_length" value="${box_width}" />
    <xacro:property name="ladle_sleeve_radius" value="${box_panel_thickness/2}" />
    <xacro:property name="ladle_sleeve_mass" value="0.5" />
    <!-- .. BRACKET (FOR LADLE) -->
    <xacro:property name="ladle_bracket_length" value="${box_bracket_ladle_width - box_panel_thickness*2}" />
    <xacro:property name="ladle_bracket_radius" value="${box_panel_thickness/2}" />
    <xacro:property name="ladle_bracket_mass" value="0.5" />
    <!-- .. BRACKET VERTICAL (FOR LADLE) -->
    <xacro:property name="ladle_bracket_vertical_mass" value="${box_panel_mass/8}" />
    <xacro:property name="ladle_bracket_vertical_depth" value="${ladle_bracket_length/1.2}" />
    <xacro:property name="ladle_bracket_vertical_width" value="${box_panel_thickness/1.2}" />
    <xacro:property name="ladle_bracket_vertical_height" value="${box_panel_thickness/1.2}" />

    <!-- SENSORS -->
    <!-- LIDAR -->
    <xacro:property name="lidar_mass" value="0.05" />
    <xacro:property name="lidar_box_panel" value="${box_panel_thickness}" />
    <!-- CAMERA -->
    <xacro:property name="camera_mass" value="0.02" />
    <xacro:property name="camera_box_panel" value="${box_panel_thickness/2}" />

</robot>
