<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:macro name="lidar_box" params="side mass surface rotate angle ray_min:='0.3' ray_max:='10' enable:='true'">
    
        <link name="${side}_lidar_box">
            <xacro:property name="reflect_" value="1"/>
            <xacro:if value="${side == 'back'}">
                <xacro:property name="reflect_" value="-1"/>
            </xacro:if>
            <visual>
                <origin rpy="${rotate}"/>
                <geometry>
                    <box size="${surface} ${surface} ${surface}"/>
                </geometry>
                <material name="GreyOne"/>
            </visual>
            <collision>
                <geometry>
                    <box size="${surface} ${surface} ${surface}"/>
                </geometry>
            </collision>
            <xacro:inertial_box 
                mass="${mass}" 
                x="${surface}"
                y="${surface}"
                z="${surface}">
                <origin xyz="0 0 0"/>
            </xacro:inertial_box>
        </link>

        <link name="${side}_lidar_led">
            <visual>
                <origin xyz="${surface/4} 0 ${surface/2}"/>
                <geometry>
                    <sphere radius="${surface/5}"/>
                </geometry>
                <material name="RedOne"/>
            </visual>
            <collision>
                <geometry>
                    <sphere radius="${surface/5}"/>
                </geometry>
            </collision>
            <inertial>
                <origin />
                <mass value="0.001" />
                <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
            </inertial>
        </link>
        <joint name="${side}_lidar_led_joint" type="fixed">
            <parent link="${side}_lidar_box"/>
            <child link="${side}_lidar_led"/>
        </joint>
        <xacro:gazeboLedLightBlock link="${side}_lidar_led"/>

        <link name="${side}_lidar_sensor"/>

        <joint name="${side}_lidar_device_joint" type="fixed">
            <parent link="${side}_lidar_box"/>
            <child link="${side}_lidar_sensor"/>
        </joint>

        <gazebo reference="${side}_lidar_sensor">
            <sensor name="laser_${side}" type="ray">
                <always_on>${enable}</always_on>
                <pose> 0 0 0 0 0 0 </pose>
                <visualize>false</visualize>
                <update_rate>10</update_rate>
                <ray>
                    <scan>
                        <horizontal>
                            <samples>${angle*2}</samples>
                            <min_angle>-${angle * pi/180}</min_angle>
                            <max_angle>${angle * pi/180}</max_angle>
                        </horizontal>
                        <!-- 
                        <vertical>
                            <samples>${angle}</samples>
                            <resolution>.5</resolution>
                            <min_angle>-0.12</min_angle>
                            <max_angle>0.0</max_angle>
                        </vertical> 
                        -->
                    </scan>
                    <range>
                        <min>${ray_min}</min>
                        <max>${ray_max}</max>
                        <resolution>0.5</resolution>
                    </range>
                </ray>
                <plugin name="laser_controller_${side}" filename="libgazebo_ros_ray_sensor.so">
                    <ros>
                        <namespace>lidar</namespace>
                        <remapping>~/out:=scan_${side}</remapping>
                    </ros>
                    <output_type>sensor_msgs/LaserScan</output_type>
                    <frame_name>${side}_lidar</frame_name>
                </plugin>
            </sensor>
        </gazebo>

    </xacro:macro>

    <!-- FRONT LIDAR -->
    <xacro:lidar_box
        side="front"
        mass="${lidar_mass}"
        surface="${lidar_box_panel}"
        rotate="0 ${pi/4} 0"
        angle="90"
        ray_min=".3"
    />
    
    <joint name="front_lidar_box_joint" type="fixed">
        <parent link="hood_top"/>
        <child link="front_lidar_box"/>
        <origin xyz="${hood_top_depth - lidar_box_panel/1.5} 0 0" />
    </joint>

    <!-- BACK LIDAR -->
    <xacro:lidar_box
        side="back"
        mass="${lidar_mass}"
        surface="${lidar_box_panel}"
        rotate="0 ${pi/4} 0"
        angle="90"
    />

    <joint name="back_lidar_box_joint" type="fixed">
        <parent link="box_panel_back"/>
        <child link="back_lidar_box"/>
        <origin xyz="-${box_panel_fb_depth/2} 0 ${box_panel_fb_height/2}" rpy="0 0 ${pi}"/>
    </joint>

</robot>
